[package]
name = "fartcode-ssh"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
fartcode-core = { path = "../fartcode-core" }
ssh-key = { workspace = true }
russh = { workspace = true }
russh-sftp = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
