//! GENERATED from `ade-providers/extracted/` (E3-01 registry data extraction).
//! Source of truth: the reference `packages/plugins/src/agents/impl/*/index.ts`.
//! To add a provider: add its descriptor here (one entry) — see `registry.rs`.

use std::sync::LazyLock;

use crate::types::{Capabilities, PromptDescriptor, PromptStrategy, ProviderDescriptor};

pub static PROVIDERS: LazyLock<Vec<ProviderDescriptor>> = LazyLock::new(|| {
    vec![
    ProviderDescriptor {
        id: "antigravity".to_string(),
        name: "Antigravity".to_string(),
        description: "Google Antigravity CLI for terminal-first agent sessions with shared Antigravity settings and conversation history.".to_string(),
        website_url: Some("https://antigravity.google/docs/cli-overview".to_string()),
        capabilities: Capabilities {
            acp: false,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: false,
            models: true,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("-i".to_string()) },
            auto_approve_flag: Some("--dangerously-skip-permissions".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("-i".to_string()),
            resume_flag: None,
            session_id_flag: Some("--conversation=".to_string()),
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: Some("--model".to_string()),
            new_conversation_flag: None,
            session_id_always: true,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["agy".to_string(), "antigravity".to_string()],
        default_model: Some("Gemini 3.5 Flash (Medium)".to_string()),
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "claude".to_string(),
        name: "Claude Code".to_string(),
        description: "CLI that uses Anthropic Claude for code edits, explanations, and structured refactors in the terminal.".to_string(),
        website_url: Some("https://code.claude.com/docs/en/quickstart".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: true,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: true,
            models: true,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: true,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: Some("--dangerously-skip-permissions".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: Some("--resume".to_string()),
            session_id_flag: Some("--session-id".to_string()),
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: Some("--model".to_string()),
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["claude".to_string()],
        default_model: Some("claude-fable-5".to_string()),
        env_vars: vec!["ANTHROPIC_API_KEY".to_string()],
    },
    ProviderDescriptor {
        id: "codex".to_string(),
        name: "Codex".to_string(),
        description: "CLI that connects to OpenAI models for project-aware code assistance and terminal workflows.".to_string(),
        website_url: Some("https://github.com/openai/codex".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: true,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: true,
            models: true,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: Some("-c approval_policy=\"never\" -c sandbox_mode=\"danger-full-access\" --dangerously-bypass-hook-trust".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: Some("resume".to_string()),
            session_id_flag: Some(" ".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: Some("resume --last".to_string()),
            model_flag: Some("-m".to_string()),
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec!["--dangerously-bypass-approvals-and-sandbox".to_string()],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["codex".to_string()],
        default_model: Some("gpt-5.6-sol".to_string()),
        env_vars: vec!["OPENAI_API_KEY".to_string()],
    },
    ProviderDescriptor {
        id: "devin".to_string(),
        name: "Devin".to_string(),
        description: "Cognition's Devin for Terminal agent for local, interactive coding sessions with Devin Cloud integration.".to_string(),
        website_url: Some("https://docs.devin.ai/cli".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("--".to_string()) },
            auto_approve_flag: Some("--permission-mode=bypass".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("--".to_string()),
            resume_flag: Some("--continue".to_string()),
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["devin".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "droid".to_string(),
        name: "Droid".to_string(),
        description: "Factory AI's agent CLI for running multi-step coding tasks from the terminal.".to_string(),
        website_url: Some("https://docs.factory.ai/cli/getting-started/quickstart".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: true,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: Some("--auto high".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: Some("--resume".to_string()),
            session_id_flag: Some("--resume".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["droid".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "grok".to_string(),
        name: "Grok".to_string(),
        description: "xAI's Grok CLI for terminal-first coding sessions with plans, subagents, and parallel work.".to_string(),
        website_url: Some("https://docs.x.ai/build/overview".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: true,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: Some("--always-approve".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: Some("-r".to_string()),
            session_id_flag: Some("-r".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: Some("-r".to_string()),
            model_flag: Some("-m".to_string()),
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["grok".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "qwen".to_string(),
        name: "Qwen Code".to_string(),
        description: "Command-line interface to Alibaba's Qwen Code models for coding assistance and code completion.".to_string(),
        website_url: Some("https://github.com/QwenLM/qwen-code".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: true,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("-i".to_string()) },
            auto_approve_flag: Some("--approval-mode=yolo".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("-i".to_string()),
            resume_flag: Some("--resume".to_string()),
            session_id_flag: Some("--resume".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: Some("--continue".to_string()),
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["qwen".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "amp".to_string(),
        name: "Amp".to_string(),
        description: "Amp Code CLI for agentic coding sessions against your repository from the terminal.".to_string(),
        website_url: Some("https://ampcode.com/manual#install".to_string()),
        capabilities: Capabilities {
            acp: false,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: true,
            models: true,
            plugins: true,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::StdinPipe,
            auto_approve_flag: Some("--dangerously-allow-all".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: None,
            resume_flag: Some("threads continue".to_string()),
            session_id_flag: Some("threads continue".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: None,
            model_flag: Some("-m".to_string()),
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: true,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["amp".to_string()],
        default_model: Some("low".to_string()),
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "charm".to_string(),
        name: "Charm".to_string(),
        description: "Charm Crush agent CLI providing terminal-first AI assistance for coding tasks.".to_string(),
        website_url: Some("https://github.com/charmbracelet/crush".to_string()),
        capabilities: Capabilities {
            acp: false,
            auth: false,
            auto_approve: false,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: true,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: None,
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: None,
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec!["run".to_string()],
        },
        binaries: vec!["crush".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "commandcode".to_string(),
        name: "Command Code".to_string(),
        description: "Command Code CLI for terminal-first coding sessions that learn project and personal coding taste.".to_string(),
        website_url: Some("https://commandcode.ai/docs/reference/cli".to_string()),
        capabilities: Capabilities {
            acp: false,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: Some("--yolo".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: Some("--resume".to_string()),
            session_id_flag: Some("--resume".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec!["--trust".to_string(), "--skip-onboarding".to_string()],
        },
        binaries: vec!["command-code".to_string(), "commandcode".to_string(), "cmdc".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "copilot".to_string(),
        name: "GitHub Copilot".to_string(),
        description: "GitHub Copilot CLI brings Copilot prompts to the terminal for code, shell, and search help.".to_string(),
        website_url: Some("https://docs.github.com/en/copilot/how-tos/set-up/install-copilot-cli".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: true,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: true,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("-i".to_string()) },
            auto_approve_flag: Some("--allow-all-tools".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("-i".to_string()),
            resume_flag: Some("--resume".to_string()),
            session_id_flag: Some("--resume".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["copilot".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "cursor".to_string(),
        name: "Cursor".to_string(),
        description: "Cursor's agent CLI; provides editor-style, project-aware assistance from the shell.".to_string(),
        website_url: Some("https://cursor.com/docs/cli/overview".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: true,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: true,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: Some("-f --approve-mcps".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: Some("--resume".to_string()),
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["cursor-agent".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "hermes".to_string(),
        name: "Hermes Agent".to_string(),
        description: "Nous Research terminal agent with interactive chat, model-provider routing, skills, and session workflows.".to_string(),
        website_url: Some("https://hermes-agent.nousresearch.com/docs/".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Keystroke,
            auto_approve_flag: Some("--yolo".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: None,
            resume_flag: Some("--continue".to_string()),
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["hermes".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "opencode".to_string(),
        name: "OpenCode".to_string(),
        description: "OpenCode CLI that interfaces with models for code generation and edits from the shell.".to_string(),
        website_url: Some("https://opencode.ai/docs/cli/".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: true,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: true,
            models: false,
            plugins: true,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("--prompt".to_string()) },
            auto_approve_flag: None,
            auto_approve_env: Some(vec![("OPENCODE_PERMISSION".to_string(), "{\"*\":\"allow\"}".to_string())]),
            initial_prompt_flag: Some("--prompt".to_string()),
            resume_flag: Some("--session".to_string()),
            session_id_flag: Some("--session".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: Some("--continue".to_string()),
            model_flag: Some("--model".to_string()),
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["opencode".to_string()],
        default_model: None,
        env_vars: vec!["ANTHROPIC_API_KEY".to_string(), "OPENAI_API_KEY".to_string(), "GEMINI_API_KEY".to_string()],
    },
    ProviderDescriptor {
        id: "auggie".to_string(),
        name: "Auggie".to_string(),
        description: "Augment Code CLI to run an agent against your repository for code changes and reviews.".to_string(),
        website_url: Some("https://docs.augmentcode.com/cli/overview".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: false,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: None,
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: Some("--resume".to_string()),
            session_id_flag: Some("--resume".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: Some("--continue".to_string()),
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec!["--allow-indexing".to_string()],
        },
        binaries: vec!["auggie".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "cline".to_string(),
        name: "Cline".to_string(),
        description: "Cline CLI runs coding agents directly in your terminal with multi-provider model support.".to_string(),
        website_url: Some("https://docs.cline.bot/cline-cli/overview".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: Some("--yolo".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: None,
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["cline".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "goose".to_string(),
        name: "Goose".to_string(),
        description: "Goose CLI that routes tasks to tools and models for coding workflows.".to_string(),
        website_url: Some("https://goose-docs.ai/docs/quickstart/".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: false,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("-t".to_string()) },
            auto_approve_flag: None,
            auto_approve_env: None,
            initial_prompt_flag: Some("-t".to_string()),
            resume_flag: Some("--resume".to_string()),
            session_id_flag: Some("--session-id".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["goose".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "kilocode".to_string(),
        name: "Kilocode".to_string(),
        description: "Kilo AI coding assistant with multiple modes, broad model support, and checkpoint-based workflows.".to_string(),
        website_url: Some("https://kilo.ai/docs/cli".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: true,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("--prompt".to_string()) },
            auto_approve_flag: Some("--auto".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("--prompt".to_string()),
            resume_flag: Some("--continue".to_string()),
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["kilo".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "kimi".to_string(),
        name: "Kimi".to_string(),
        description: "Kimi CLI by Moonshot AI, with shell execution, Zsh integration, ACP, and MCP support.".to_string(),
        website_url: Some("https://moonshotai.github.io/kimi-cli/en/guides/getting-started.html".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Keystroke,
            auto_approve_flag: Some("--yolo".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: None,
            resume_flag: Some("-S".to_string()),
            session_id_flag: Some("-S".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: Some("-C".to_string()),
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: true,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["kimi".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "kiro".to_string(),
        name: "Kiro (AWS)".to_string(),
        description: "Kiro CLI by AWS, focused on interactive terminal-first development assistance and workflow automation.".to_string(),
        website_url: Some("https://kiro.dev/docs/cli/".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: Some("--trust-all-tools".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: Some("--resume-id".to_string()),
            session_id_flag: Some("--resume-id".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: Some("--resume".to_string()),
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec!["chat".to_string(), "--agent".to_string(), "emdash".to_string()],
        },
        binaries: vec!["kiro-cli".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "rovo".to_string(),
        name: "Rovo Dev".to_string(),
        description: "Atlassian Rovo Dev CLI integrates terminal assistance with Jira, Confluence, and Bitbucket workflows.".to_string(),
        website_url: Some("https://support.atlassian.com/rovo/docs/install-and-run-rovo-dev-cli-on-your-device/".to_string()),
        capabilities: Capabilities {
            acp: false,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: Some("--yolo".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: None,
            resume_flag: None,
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["rovodev".to_string(), "acli".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "codebuddy".to_string(),
        name: "CodeBuddy Code".to_string(),
        description: "Tencent's terminal coding agent for repository-aware implementation, debugging, and code analysis.".to_string(),
        website_url: Some("https://www.codebuddy.ai/docs/cli/README".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: true,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: Some("--dangerously-skip-permissions".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: Some("--resume".to_string()),
            session_id_flag: Some("--session-id".to_string()),
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: Some("--model".to_string()),
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["codebuddy".to_string(), "cbc".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "codebuff".to_string(),
        name: "Codebuff".to_string(),
        description: "Codebuff is an AI coding agent for project-directory assistance and day-to-day development tasks.".to_string(),
        website_url: Some("https://www.codebuff.com/docs/help/quick-start".to_string()),
        capabilities: Capabilities {
            acp: false,
            auth: false,
            auto_approve: false,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: None,
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: None,
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["codebuff".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "continue".to_string(),
        name: "Continue".to_string(),
        description: "Continue CLI is a modular coding agent with configurable models, rules, and MCP tool support.".to_string(),
        website_url: Some("https://docs.continue.dev/guides/cli".to_string()),
        capabilities: Capabilities {
            acp: false,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: Some("--auto".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: Some("--resume".to_string()),
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["cn".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "freebuff".to_string(),
        name: "Freebuff".to_string(),
        description: "Freebuff is a standalone Codebuff package for project-directory assistance and day-to-day development tasks.".to_string(),
        website_url: Some("https://freebuff.com".to_string()),
        capabilities: Capabilities {
            acp: false,
            auth: false,
            auto_approve: false,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Keystroke,
            auto_approve_flag: None,
            auto_approve_env: None,
            initial_prompt_flag: None,
            resume_flag: None,
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["freebuff".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "jules".to_string(),
        name: "Jules".to_string(),
        description: "Google's Jules CLI for managing asynchronous remote coding sessions and a terminal dashboard.".to_string(),
        website_url: Some("https://jules.google/docs/cli/reference/".to_string()),
        capabilities: Capabilities {
            acp: false,
            auth: false,
            auto_approve: false,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Keystroke,
            auto_approve_flag: None,
            auto_approve_env: None,
            initial_prompt_flag: None,
            resume_flag: None,
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["jules".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "junie".to_string(),
        name: "Junie".to_string(),
        description: "JetBrains agentic coding CLI for interactive terminal and headless project workflows.".to_string(),
        website_url: Some("https://junie.jetbrains.com/docs/junie-cli.html".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: false,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("--task".to_string()) },
            auto_approve_flag: None,
            auto_approve_env: None,
            initial_prompt_flag: Some("--task".to_string()),
            resume_flag: None,
            session_id_flag: Some("--session-id".to_string()),
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["junie".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "mistral".to_string(),
        name: "Mistral Vibe".to_string(),
        description: "Mistral AI terminal coding assistant with conversational codebase help, execution tools, and file operations.".to_string(),
        website_url: Some("https://github.com/mistralai/mistral-vibe".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: false,
            models: true,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: Some("--agent auto-approve".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: None,
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["vibe".to_string()],
        default_model: Some("mistral-medium-3.5".to_string()),
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "autohand".to_string(),
        name: "Autohand Code".to_string(),
        description: "Terminal coding agent with auto-commit, dry-run previews, community skills, and headless automation modes.".to_string(),
        website_url: Some("https://autohand.ai/code/".to_string()),
        capabilities: Capabilities {
            acp: false,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("-p".to_string()) },
            auto_approve_flag: Some("--unrestricted".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("-p".to_string()),
            resume_flag: None,
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["autohand".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "letta".to_string(),
        name: "Letta".to_string(),
        description: "Memory-first coding agent CLI with persistent agents that learn across sessions and portable memory across models.".to_string(),
        website_url: Some("https://docs.letta.com/letta-code/cli".to_string()),
        capabilities: Capabilities {
            acp: false,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Keystroke,
            auto_approve_flag: Some("--yolo".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: None,
            resume_flag: None,
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: Some("--new".to_string()),
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["letta".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "mimocode".to_string(),
        name: "MiMo Code".to_string(),
        description: "Xiaomi's terminal-native coding agent with persistent cross-session memory and OpenAI-compatible provider support.".to_string(),
        website_url: Some("https://github.com/XiaomiMiMo/MiMo-Code".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: true,
            models: false,
            plugins: true,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("--prompt".to_string()) },
            auto_approve_flag: None,
            auto_approve_env: Some(vec![("MIMOCODE_PERMISSION".to_string(), "{\"*\":\"allow\"}".to_string())]),
            initial_prompt_flag: Some("--prompt".to_string()),
            resume_flag: Some("--session".to_string()),
            session_id_flag: Some("--session".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: Some("--continue".to_string()),
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["mimo".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "oh-my-pi".to_string(),
        name: "Oh My Pi".to_string(),
        description: "Terminal-first coding agent with LSP, debugger, subagents, browser tools, and ACP support.".to_string(),
        website_url: Some("https://omp.sh".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: false,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: true,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: None,
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: Some("--session".to_string()),
            session_id_flag: Some("--session".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: None,
            model_flag: Some("--model".to_string()),
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec!["--extension".to_string(), "./.omp/extensions/emdash-hook.ts".to_string()],
        },
        binaries: vec!["omp".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "pi".to_string(),
        name: "Pi".to_string(),
        description: "Minimal terminal coding agent with multi-provider model support and extensible custom tools.".to_string(),
        website_url: Some("https://github.com/earendil-works/pi/tree/main/packages/coding-agent".to_string()),
        capabilities: Capabilities {
            acp: false,
            auth: false,
            auto_approve: false,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: true,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: None,
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: Some("--session".to_string()),
            session_id_flag: Some("--session".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["pi".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "qoder".to_string(),
        name: "Qoder CLI".to_string(),
        description: "Qoder terminal agent for code review, implementation, debugging, and repository-aware automation.".to_string(),
        website_url: Some("https://qoder.com/en/cli".to_string()),
        capabilities: Capabilities {
            acp: true,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: true,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Argv { flag: Some("".to_string()) },
            auto_approve_flag: Some("--yolo".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: Some("".to_string()),
            resume_flag: Some("-r".to_string()),
            session_id_flag: Some("-r".to_string()),
            session_id_on_resume_only: true,
            resume_without_session_flag: Some("-c".to_string()),
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["qodercli".to_string()],
        default_model: None,
        env_vars: vec![],
    },
    ProviderDescriptor {
        id: "zero".to_string(),
        name: "Zero".to_string(),
        description: "Terminal coding agent with multi-provider model support, local-first configuration, and terminal-first coding workflows.".to_string(),
        website_url: Some("https://zero.gitlawb.com/".to_string()),
        capabilities: Capabilities {
            acp: false,
            auth: false,
            auto_approve: true,
            effort: false,
            hooks: false,
            host_dependency: true,
            mcp: false,
            models: false,
            plugins: false,
            prompt: true,
            sessions: true,
            trust: false,
        },
        prompt: PromptDescriptor {
            strategy: PromptStrategy::Keystroke,
            auto_approve_flag: Some("--skip-permissions-unsafe".to_string()),
            auto_approve_env: None,
            initial_prompt_flag: None,
            resume_flag: None,
            session_id_flag: None,
            session_id_on_resume_only: false,
            resume_without_session_flag: None,
            model_flag: None,
            new_conversation_flag: None,
            session_id_always: false,
            omit_auto_approve_on_resume: false,
            initial_prompt_via_stdin_pipe: false,
            deduplicate_flags: vec![],
            submit_sequence: None,
            submit_delay_ms: None,
            default_args: vec![],
        },
        binaries: vec!["zero".to_string()],
        default_model: None,
        env_vars: vec![],
    }
]
});
